version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "02:00"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "02:00"
    open-pull-requests-limit: 100
